/**
 * Model Profiles — Per-model visual characteristics for procedural generation.
 *
 * Each profile defines proportions, colors, and distinctive features
 * that produce recognizable silhouettes for each of the 145 Alice models.
 */

import type { EntityCategory } from "./types.js";

// ── Profile Types ──────────────────────────────────────────────────

export interface BodyProportions {
  /** Overall height multiplier (1.0 = standard for category) */
  readonly height: number;
  /** Width multiplier relative to height */
  readonly width: number;
  /** Depth multiplier relative to height */
  readonly depth: number;
}

export interface HeadProfile {
  /** Head size relative to body (1.0 = standard) */
  readonly size: number;
  /** Head shape: sphere, elongated (snout), flat */
  readonly shape: "sphere" | "elongated" | "flat" | "pointed";
  /** Vertical offset from neck attachment */
  readonly yOffset: number;
}

export interface LimbProfile {
  /** Limb thickness (1.0 = standard) */
  readonly thickness: number;
  /** Limb length (1.0 = standard) */
  readonly length: number;
}

export interface DistinctiveFeature {
  /** Feature type determines how it's rendered */
  readonly type: "horn" | "ears" | "tail" | "wings" | "hump" | "trunk" | "mane"
    | "shell" | "fin" | "crest" | "beak" | "antlers" | "tusks" | "collar"
    | "hat" | "cape" | "crown" | "armor" | "sword" | "staff" | "shield"
    | "mushroom_cap" | "flat_top" | "canopy" | "chimney" | "rotor"
    | "balloon" | "mast" | "sail" | "periscope" | "funnel" | "smokestack"
    | "propeller" | "pontoons" | "cabin_tall" | "flatbed" | "light_bar"
    | "bumper" | "spoiler" | "tank" | "box_car" | "wheels_large" | "piano_keys"
    | "screen" | "cushion" | "shelf" | "barrel" | "spout" | "glow";
  /** Scale of the feature (1.0 = standard) */
  readonly scale: number;
  /** Position offset {x, y, z} relative to attachment point */
  readonly offset?: { x: number; y: number; z: number };
}

export interface ModelProfile {
  readonly id: string;
  readonly name: string;
  readonly category: EntityCategory;
  /** Primary body color as packed hex */
  readonly primaryColor: number;
  /** Secondary/accent color as packed hex */
  readonly secondaryColor: number;
  readonly body: BodyProportions;
  readonly head: HeadProfile;
  readonly limbs: LimbProfile;
  /** Distinctive features that make this model recognizable */
  readonly features: readonly DistinctiveFeature[];
}

// ── Helper ─────────────────────────────────────────────────────────

function profile(
  id: string,
  name: string,
  category: EntityCategory,
  primaryColor: number,
  secondaryColor: number,
  body: BodyProportions,
  head: HeadProfile,
  limbs: LimbProfile,
  features: DistinctiveFeature[] = [],
): ModelProfile {
  return { id, name, category, primaryColor, secondaryColor, body, head, limbs, features };
}

const STD_BODY: BodyProportions = { height: 1.0, width: 1.0, depth: 1.0 };
const STD_HEAD: HeadProfile = { size: 1.0, shape: "sphere", yOffset: 0 };
const STD_LIMBS: LimbProfile = { thickness: 1.0, length: 1.0 };

// ── Biped Profiles ─────────────────────────────────────────────────

export const BIPED_PROFILES: readonly ModelProfile[] = [
  profile("ALIEN", "Alien", "BIPED", 0x7FBF7F, 0x33AA33,
    { height: 1.0, width: 0.8, depth: 0.7 },
    { size: 1.6, shape: "sphere", yOffset: 0.1 },
    { thickness: 0.7, length: 1.0 }, []),
  profile("BUNNY", "Bunny", "BIPED", 0xE8D8C8, 0xFFCCCC,
    { height: 0.7, width: 0.9, depth: 1.0 },
    { size: 1.1, shape: "sphere", yOffset: 0 },
    { thickness: 0.9, length: 0.8 },
    [{ type: "ears", scale: 1.8 }]),
  profile("CHEF", "Chef", "BIPED", 0xFFFFFF, 0xCC2222,
    STD_BODY, STD_HEAD, STD_LIMBS,
    [{ type: "hat", scale: 1.5 }]),
  profile("CHILD", "Child", "BIPED", 0x6699CC, 0xFFCC66,
    { height: 0.7, width: 0.85, depth: 0.85 },
    { size: 1.2, shape: "sphere", yOffset: 0 },
    { thickness: 0.8, length: 0.75 }, []),
  profile("DRAGON_BABY", "Dragon Baby", "BIPED", 0x66BB66, 0xBB4444,
    { height: 0.6, width: 1.0, depth: 1.1 },
    { size: 1.3, shape: "elongated", yOffset: 0 },
    { thickness: 0.9, length: 0.7 },
    [{ type: "wings", scale: 0.8 }, { type: "tail", scale: 0.6 }]),
  profile("ELF", "Elf", "BIPED", 0x33AA55, 0xDDCC88,
    { height: 0.85, width: 0.8, depth: 0.8 },
    { size: 0.9, shape: "pointed", yOffset: 0 },
    { thickness: 0.75, length: 0.9 },
    [{ type: "ears", scale: 1.2 }]),
  profile("FAIRY", "Fairy", "BIPED", 0xEE88DD, 0xFFDDFF,
    { height: 0.5, width: 0.7, depth: 0.7 },
    { size: 1.1, shape: "sphere", yOffset: 0 },
    { thickness: 0.6, length: 0.8 },
    [{ type: "wings", scale: 1.5 }]),
  profile("GHOST", "Ghost", "BIPED", 0xDDDDEE, 0xAAAACC,
    { height: 1.1, width: 1.1, depth: 0.9 },
    { size: 1.0, shape: "sphere", yOffset: 0.1 },
    { thickness: 0.0, length: 0.0 },  // no visible limbs
    [{ type: "cape", scale: 1.5 }]),
  profile("KNIGHT", "Knight", "BIPED", 0x888899, 0x666677,
    { height: 1.1, width: 1.15, depth: 1.1 },
    { size: 1.0, shape: "flat", yOffset: 0 },
    { thickness: 1.2, length: 1.0 },
    [{ type: "armor", scale: 1.0 }, { type: "sword", scale: 1.0 }]),
  profile("LION_BIPED", "Lion Biped", "BIPED", 0xCC9944, 0x885522,
    { height: 1.05, width: 1.1, depth: 1.0 },
    { size: 1.2, shape: "sphere", yOffset: 0 },
    { thickness: 1.0, length: 1.0 },
    [{ type: "mane", scale: 1.3 }, { type: "tail", scale: 0.8 }]),
  profile("MADHATTER", "Mad Hatter", "BIPED", 0x9955BB, 0x44BB77,
    { height: 1.1, width: 0.9, depth: 0.9 },
    STD_HEAD, STD_LIMBS,
    [{ type: "hat", scale: 2.0 }]),
  profile("MUMMY", "Mummy", "BIPED", 0xCCBB99, 0xAA9966,
    STD_BODY,
    { size: 0.95, shape: "sphere", yOffset: 0 },
    STD_LIMBS, []),
  profile("OGRE", "Ogre", "BIPED", 0x88AA44, 0x667733,
    { height: 1.3, width: 1.4, depth: 1.3 },
    { size: 1.1, shape: "sphere", yOffset: -0.05 },
    { thickness: 1.5, length: 1.0 }, []),
  profile("PENGUIN", "Penguin", "BIPED", 0x222222, 0xFFFFFF,
    { height: 0.7, width: 0.85, depth: 0.9 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.8, length: 0.6 },
    [{ type: "beak", scale: 0.6 }]),
  profile("PIRATE", "Pirate", "BIPED", 0x884422, 0xCC2222,
    STD_BODY, STD_HEAD, STD_LIMBS,
    [{ type: "hat", scale: 1.2 }, { type: "sword", scale: 0.8 }]),
  profile("PRINCESS", "Princess", "BIPED", 0xFFAACC, 0xFFDD88,
    { height: 1.0, width: 0.9, depth: 0.85 },
    STD_HEAD, { thickness: 0.8, length: 1.0 },
    [{ type: "crown", scale: 0.8 }, { type: "cape", scale: 1.0 }]),
  profile("QUEEN_OF_HEARTS", "Queen of Hearts", "BIPED", 0xCC2222, 0xFFDD00,
    { height: 1.1, width: 1.1, depth: 1.0 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.9, length: 1.0 },
    [{ type: "crown", scale: 1.2 }, { type: "collar", scale: 1.5 }]),
  profile("ROBOT", "Robot", "BIPED", 0x999999, 0x44AAFF,
    { height: 1.05, width: 1.1, depth: 1.0 },
    { size: 1.0, shape: "flat", yOffset: 0 },
    { thickness: 1.2, length: 1.0 }, []),
  profile("SKELETON", "Skeleton", "BIPED", 0xEEDDCC, 0xCCBBAA,
    { height: 1.05, width: 0.75, depth: 0.7 },
    { size: 1.1, shape: "sphere", yOffset: 0 },
    { thickness: 0.5, length: 1.0 }, []),
  profile("TROLL", "Troll", "BIPED", 0x556644, 0x778855,
    { height: 0.9, width: 1.3, depth: 1.2 },
    { size: 0.9, shape: "sphere", yOffset: 0 },
    { thickness: 1.4, length: 0.85 }, []),
  profile("WITCH", "Witch", "BIPED", 0x333333, 0x44BB44,
    { height: 1.0, width: 0.85, depth: 0.85 },
    { size: 0.9, shape: "pointed", yOffset: 0 },
    { thickness: 0.8, length: 1.0 },
    [{ type: "hat", scale: 1.8 }, { type: "staff", scale: 1.0 }]),
  profile("WIZARD", "Wizard", "BIPED", 0x4444BB, 0xFFDD44,
    { height: 1.1, width: 0.9, depth: 0.9 },
    STD_HEAD, { thickness: 0.8, length: 1.0 },
    [{ type: "hat", scale: 1.6 }, { type: "staff", scale: 1.2 }]),
  profile("YETI", "Yeti", "BIPED", 0xDDDDEE, 0xBBBBCC,
    { height: 1.4, width: 1.5, depth: 1.3 },
    { size: 1.0, shape: "sphere", yOffset: -0.05 },
    { thickness: 1.4, length: 1.1 }, []),
  profile("ZOMBIE", "Zombie", "BIPED", 0x77AA77, 0x557755,
    STD_BODY,
    { size: 0.95, shape: "sphere", yOffset: 0 },
    STD_LIMBS, []),
];

// ── Flyer Profiles ─────────────────────────────────────────────────

export const FLYER_PROFILES: readonly ModelProfile[] = [
  profile("BAT", "Bat", "FLYER", 0x443333, 0x332222,
    { height: 0.6, width: 1.0, depth: 0.8 },
    { size: 0.8, shape: "sphere", yOffset: 0 },
    { thickness: 0.5, length: 0.6 },
    [{ type: "wings", scale: 2.0 }, { type: "ears", scale: 0.8 }]),
  profile("BLUEJAY", "Bluejay", "FLYER", 0x3377CC, 0xDDDDDD,
    { height: 0.5, width: 0.8, depth: 0.8 },
    { size: 0.9, shape: "sphere", yOffset: 0 },
    { thickness: 0.6, length: 0.5 },
    [{ type: "beak", scale: 0.5 }, { type: "crest", scale: 0.6 }]),
  profile("CHICKEN", "Chicken", "FLYER", 0xDD9944, 0xCC3333,
    { height: 0.7, width: 1.1, depth: 1.0 },
    { size: 0.8, shape: "sphere", yOffset: 0 },
    { thickness: 0.8, length: 0.7 },
    [{ type: "beak", scale: 0.4 }, { type: "crest", scale: 0.8 }]),
  profile("CRANE", "Crane", "FLYER", 0xEEEEEE, 0xCC3333,
    { height: 1.2, width: 0.7, depth: 0.7 },
    { size: 0.7, shape: "elongated", yOffset: 0 },
    { thickness: 0.5, length: 1.5 },
    [{ type: "beak", scale: 1.2 }]),
  profile("CROW", "Crow", "FLYER", 0x222222, 0x333344,
    { height: 0.6, width: 0.9, depth: 0.9 },
    { size: 0.85, shape: "sphere", yOffset: 0 },
    { thickness: 0.6, length: 0.6 },
    [{ type: "beak", scale: 0.6 }]),
  profile("EAGLE", "Eagle", "FLYER", 0x553311, 0xFFFFFF,
    { height: 0.8, width: 1.0, depth: 1.0 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.7, length: 0.7 },
    [{ type: "beak", scale: 0.8 }, { type: "wings", scale: 1.6 }]),
  profile("FALCON", "Falcon", "FLYER", 0x665544, 0xCCBB99,
    { height: 0.7, width: 0.9, depth: 0.9 },
    { size: 0.9, shape: "sphere", yOffset: 0 },
    { thickness: 0.6, length: 0.7 },
    [{ type: "beak", scale: 0.6 }, { type: "wings", scale: 1.4 }]),
  profile("FLAMINGO", "Flamingo", "FLYER", 0xFF88AA, 0xFF5588,
    { height: 1.4, width: 0.6, depth: 0.6 },
    { size: 0.7, shape: "elongated", yOffset: 0 },
    { thickness: 0.4, length: 1.8 },
    [{ type: "beak", scale: 0.8 }]),
  profile("HAWK", "Hawk", "FLYER", 0x774422, 0xCCBB99,
    { height: 0.7, width: 1.0, depth: 1.0 },
    { size: 0.9, shape: "sphere", yOffset: 0 },
    { thickness: 0.6, length: 0.7 },
    [{ type: "beak", scale: 0.7 }, { type: "wings", scale: 1.5 }]),
  profile("HUMMINGBIRD", "Hummingbird", "FLYER", 0x22CC77, 0xFF4444,
    { height: 0.3, width: 0.5, depth: 0.5 },
    { size: 0.8, shape: "sphere", yOffset: 0 },
    { thickness: 0.4, length: 0.4 },
    [{ type: "beak", scale: 1.4 }, { type: "wings", scale: 1.0 }]),
  profile("OWL", "Owl", "FLYER", 0x886644, 0xFFDD88,
    { height: 0.7, width: 1.0, depth: 1.0 },
    { size: 1.3, shape: "flat", yOffset: 0 },
    { thickness: 0.7, length: 0.5 },
    [{ type: "ears", scale: 0.6 }]),
  profile("PARROT", "Parrot", "FLYER", 0x22BB22, 0xCC2222,
    { height: 0.6, width: 0.8, depth: 0.9 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.6, length: 0.6 },
    [{ type: "beak", scale: 0.7 }, { type: "crest", scale: 0.7 }]),
  profile("PEACOCK", "Peacock", "FLYER", 0x2244AA, 0x22CCAA,
    { height: 0.9, width: 1.0, depth: 1.0 },
    { size: 0.8, shape: "sphere", yOffset: 0 },
    { thickness: 0.6, length: 0.8 },
    [{ type: "crest", scale: 1.0 }, { type: "tail", scale: 2.5 }]),
  profile("PELICAN", "Pelican", "FLYER", 0xDDDDDD, 0xFFBB44,
    { height: 0.8, width: 1.1, depth: 1.1 },
    { size: 1.1, shape: "elongated", yOffset: 0 },
    { thickness: 0.7, length: 0.6 },
    [{ type: "beak", scale: 1.6 }]),
  profile("PHOENIX", "Phoenix", "FLYER", 0xFF6622, 0xFFCC00,
    { height: 0.9, width: 1.0, depth: 1.0 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.7, length: 0.8 },
    [{ type: "wings", scale: 1.8 }, { type: "tail", scale: 1.5 }, { type: "crest", scale: 1.0 }]),
  profile("PIGEON", "Pigeon", "FLYER", 0x889999, 0x667788,
    { height: 0.5, width: 0.9, depth: 0.9 },
    { size: 0.85, shape: "sphere", yOffset: 0 },
    { thickness: 0.6, length: 0.5 },
    [{ type: "beak", scale: 0.4 }]),
  profile("PTERODACTYL", "Pterodactyl", "FLYER", 0x889966, 0x667744,
    { height: 0.8, width: 1.0, depth: 1.0 },
    { size: 1.0, shape: "elongated", yOffset: 0 },
    { thickness: 0.7, length: 0.7 },
    [{ type: "wings", scale: 2.2 }, { type: "crest", scale: 1.2 }]),
  profile("SEAGULL", "Seagull", "FLYER", 0xEEEEEE, 0x888888,
    { height: 0.5, width: 0.9, depth: 0.9 },
    { size: 0.85, shape: "sphere", yOffset: 0 },
    { thickness: 0.6, length: 0.5 },
    [{ type: "beak", scale: 0.6 }]),
  profile("SPARROW", "Sparrow", "FLYER", 0x885533, 0xCCBB88,
    { height: 0.4, width: 0.7, depth: 0.7 },
    { size: 0.85, shape: "sphere", yOffset: 0 },
    { thickness: 0.5, length: 0.4 },
    [{ type: "beak", scale: 0.4 }]),
  profile("TOUCAN", "Toucan", "FLYER", 0x222222, 0xFF8800,
    { height: 0.6, width: 0.8, depth: 0.9 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.6, length: 0.6 },
    [{ type: "beak", scale: 2.0 }]),
  profile("VULTURE", "Vulture", "FLYER", 0x553322, 0xCC8877,
    { height: 0.8, width: 1.0, depth: 1.0 },
    { size: 0.9, shape: "sphere", yOffset: 0 },
    { thickness: 0.7, length: 0.7 },
    [{ type: "wings", scale: 1.7 }]),
];

// ── Quadruped Profiles ─────────────────────────────────────────────

export const QUADRUPED_PROFILES: readonly ModelProfile[] = [
  profile("BEAR", "Bear", "QUADRUPED", 0x664422, 0x553311,
    { height: 1.2, width: 1.3, depth: 1.2 },
    { size: 1.2, shape: "sphere", yOffset: 0 },
    { thickness: 1.4, length: 0.9 },
    [{ type: "ears", scale: 0.5 }]),
  profile("CAMEL", "Camel", "QUADRUPED", 0xBB9966, 0xAA8855,
    { height: 1.3, width: 1.0, depth: 1.0 },
    { size: 0.8, shape: "elongated", yOffset: 0.1 },
    { thickness: 0.8, length: 1.3 },
    [{ type: "hump", scale: 1.2 }]),
  profile("CAT", "Cat", "QUADRUPED", 0xDD8833, 0xEECC88,
    { height: 0.6, width: 0.8, depth: 0.9 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.7, length: 0.7 },
    [{ type: "ears", scale: 0.8 }, { type: "tail", scale: 1.2 }]),
  profile("CHESHIRE_CAT", "Cheshire Cat", "QUADRUPED", 0xCC44CC, 0xFF88FF,
    { height: 0.65, width: 0.85, depth: 0.9 },
    { size: 1.2, shape: "sphere", yOffset: 0.05 },
    { thickness: 0.7, length: 0.7 },
    [{ type: "ears", scale: 0.9 }, { type: "tail", scale: 1.3 }]),
  profile("COW", "Cow", "QUADRUPED", 0xEEEEEE, 0x332222,
    { height: 1.1, width: 1.2, depth: 1.1 },
    { size: 1.0, shape: "elongated", yOffset: 0 },
    { thickness: 1.0, length: 1.0 },
    [{ type: "horn", scale: 0.5 }, { type: "tail", scale: 0.7 }]),
  profile("DALMATIAN", "Dalmatian", "QUADRUPED", 0xEEEEEE, 0x222222,
    { height: 0.9, width: 0.9, depth: 0.9 },
    { size: 0.9, shape: "elongated", yOffset: 0 },
    { thickness: 0.7, length: 1.0 },
    [{ type: "ears", scale: 0.7 }, { type: "tail", scale: 0.8 }]),
  profile("DEER", "Deer", "QUADRUPED", 0xBB8844, 0xEEDDBB,
    { height: 1.1, width: 0.8, depth: 0.8 },
    { size: 0.8, shape: "elongated", yOffset: 0 },
    { thickness: 0.6, length: 1.2 },
    [{ type: "antlers", scale: 1.2 }, { type: "tail", scale: 0.3 }]),
  profile("DINOSAUR", "Dinosaur", "QUADRUPED", 0x558844, 0x446633,
    { height: 1.4, width: 1.3, depth: 1.4 },
    { size: 0.9, shape: "elongated", yOffset: 0 },
    { thickness: 1.3, length: 1.0 },
    [{ type: "tail", scale: 1.8 }, { type: "crest", scale: 0.6 }]),
  profile("DOG", "Dog", "QUADRUPED", 0xBB8844, 0xDDBB88,
    { height: 0.8, width: 0.9, depth: 0.9 },
    { size: 0.9, shape: "elongated", yOffset: 0 },
    { thickness: 0.7, length: 0.9 },
    [{ type: "ears", scale: 0.7 }, { type: "tail", scale: 0.9 }]),
  profile("DRAGON", "Dragon", "QUADRUPED", 0x448844, 0xCC4422,
    { height: 1.5, width: 1.3, depth: 1.4 },
    { size: 1.0, shape: "elongated", yOffset: 0.1 },
    { thickness: 1.1, length: 1.0 },
    [{ type: "wings", scale: 2.0 }, { type: "tail", scale: 1.5 }, { type: "horn", scale: 0.6 }]),
  profile("ELEPHANT", "Elephant", "QUADRUPED", 0x888899, 0x777788,
    { height: 1.5, width: 1.6, depth: 1.4 },
    { size: 1.2, shape: "sphere", yOffset: 0 },
    { thickness: 1.6, length: 1.0 },
    [{ type: "trunk", scale: 1.5 }, { type: "ears", scale: 2.0 }, { type: "tusks", scale: 0.8 }]),
  profile("FOX", "Fox", "QUADRUPED", 0xDD6622, 0xEEEEEE,
    { height: 0.7, width: 0.8, depth: 0.9 },
    { size: 0.9, shape: "pointed", yOffset: 0 },
    { thickness: 0.6, length: 0.9 },
    [{ type: "ears", scale: 1.0 }, { type: "tail", scale: 1.4 }]),
  profile("GIRAFFE", "Giraffe", "QUADRUPED", 0xDDBB55, 0x885522,
    { height: 2.0, width: 0.7, depth: 0.8 },
    { size: 0.7, shape: "elongated", yOffset: 0.3 },
    { thickness: 0.5, length: 1.6 },
    [{ type: "horn", scale: 0.3 }]),
  profile("GOAT", "Goat", "QUADRUPED", 0xCCBBAA, 0x887766,
    { height: 0.9, width: 0.9, depth: 0.9 },
    { size: 0.9, shape: "elongated", yOffset: 0 },
    { thickness: 0.7, length: 0.9 },
    [{ type: "horn", scale: 0.6 }, { type: "ears", scale: 0.6 }]),
  profile("GORILLA", "Gorilla", "QUADRUPED", 0x444444, 0x555555,
    { height: 1.3, width: 1.5, depth: 1.3 },
    { size: 1.1, shape: "sphere", yOffset: -0.05 },
    { thickness: 1.5, length: 0.9 }, []),
  profile("HIPPO", "Hippo", "QUADRUPED", 0x887788, 0x776677,
    { height: 1.1, width: 1.5, depth: 1.3 },
    { size: 1.3, shape: "elongated", yOffset: -0.05 },
    { thickness: 1.5, length: 0.8 },
    [{ type: "ears", scale: 0.4 }]),
  profile("HORSE", "Horse", "QUADRUPED", 0x884422, 0x663311,
    { height: 1.2, width: 0.9, depth: 1.0 },
    { size: 0.8, shape: "elongated", yOffset: 0.1 },
    { thickness: 0.7, length: 1.2 },
    [{ type: "mane", scale: 1.0 }, { type: "tail", scale: 1.2 }]),
  profile("LEOPARD", "Leopard", "QUADRUPED", 0xDDBB55, 0x553311,
    { height: 0.85, width: 0.9, depth: 1.1 },
    { size: 0.9, shape: "sphere", yOffset: 0 },
    { thickness: 0.7, length: 1.0 },
    [{ type: "tail", scale: 1.3 }]),
  profile("LION", "Lion", "QUADRUPED", 0xCC9933, 0x885522,
    { height: 1.1, width: 1.1, depth: 1.1 },
    { size: 1.2, shape: "sphere", yOffset: 0 },
    { thickness: 0.9, length: 1.0 },
    [{ type: "mane", scale: 1.5 }, { type: "tail", scale: 1.0 }]),
  profile("MOOSE", "Moose", "QUADRUPED", 0x664433, 0x553322,
    { height: 1.4, width: 1.1, depth: 1.0 },
    { size: 0.9, shape: "elongated", yOffset: 0 },
    { thickness: 0.8, length: 1.3 },
    [{ type: "antlers", scale: 2.0 }]),
  profile("MOUSE", "Mouse", "QUADRUPED", 0xBBAAAA, 0xFFCCCC,
    { height: 0.3, width: 0.6, depth: 0.7 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.5, length: 0.4 },
    [{ type: "ears", scale: 1.5 }, { type: "tail", scale: 1.8 }]),
  profile("PIG", "Pig", "QUADRUPED", 0xFFAABB, 0xFF8899,
    { height: 0.8, width: 1.2, depth: 1.1 },
    { size: 1.0, shape: "sphere", yOffset: -0.05 },
    { thickness: 0.9, length: 0.7 },
    [{ type: "ears", scale: 0.6 }, { type: "tail", scale: 0.3 }]),
  profile("POODLE", "Poodle", "QUADRUPED", 0xEEEEEE, 0xDDDDDD,
    { height: 0.8, width: 0.8, depth: 0.8 },
    { size: 1.1, shape: "sphere", yOffset: 0.05 },
    { thickness: 0.6, length: 1.0 },
    [{ type: "ears", scale: 0.8 }, { type: "tail", scale: 0.5 }]),
  profile("RABBIT", "Rabbit", "QUADRUPED", 0xDDCCBB, 0xFFCCCC,
    { height: 0.5, width: 0.8, depth: 0.9 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.7, length: 0.6 },
    [{ type: "ears", scale: 2.0 }, { type: "tail", scale: 0.2 }]),
  profile("RACCOON", "Raccoon", "QUADRUPED", 0x777777, 0x333333,
    { height: 0.6, width: 0.9, depth: 0.9 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.7, length: 0.7 },
    [{ type: "tail", scale: 1.3 }]),
  profile("RHINO", "Rhino", "QUADRUPED", 0x888888, 0x666666,
    { height: 1.2, width: 1.4, depth: 1.3 },
    { size: 1.0, shape: "elongated", yOffset: 0 },
    { thickness: 1.4, length: 0.9 },
    [{ type: "horn", scale: 1.0 }]),
  profile("SCOTTISH_FOLD", "Scottish Fold", "QUADRUPED", 0xCCBB99, 0xAA9977,
    { height: 0.55, width: 0.85, depth: 0.9 },
    { size: 1.1, shape: "sphere", yOffset: 0 },
    { thickness: 0.7, length: 0.65 },
    [{ type: "ears", scale: 0.4 }, { type: "tail", scale: 1.1 }]),
  profile("SHEEP", "Sheep", "QUADRUPED", 0xEEEEDD, 0xDDDDCC,
    { height: 0.9, width: 1.2, depth: 1.1 },
    { size: 0.9, shape: "sphere", yOffset: 0 },
    { thickness: 0.8, length: 0.8 }, []),
  profile("TIGER", "Tiger", "QUADRUPED", 0xDD8822, 0x222222,
    { height: 1.0, width: 1.1, depth: 1.2 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.9, length: 1.0 },
    [{ type: "tail", scale: 1.2 }]),
  profile("UNICORN", "Unicorn", "QUADRUPED", 0xEEEEFF, 0xCCBBFF,
    { height: 1.2, width: 0.9, depth: 1.0 },
    { size: 0.85, shape: "elongated", yOffset: 0.1 },
    { thickness: 0.7, length: 1.2 },
    [{ type: "horn", scale: 1.0 }, { type: "mane", scale: 1.2 }, { type: "tail", scale: 1.3 }]),
  profile("WOLF", "Wolf", "QUADRUPED", 0x777788, 0x555566,
    { height: 0.95, width: 0.9, depth: 1.0 },
    { size: 0.9, shape: "elongated", yOffset: 0 },
    { thickness: 0.7, length: 1.0 },
    [{ type: "ears", scale: 0.8 }, { type: "tail", scale: 1.1 }]),
  profile("ZEBRA", "Zebra", "QUADRUPED", 0xEEEEEE, 0x222222,
    { height: 1.1, width: 0.9, depth: 1.0 },
    { size: 0.8, shape: "elongated", yOffset: 0 },
    { thickness: 0.7, length: 1.1 },
    [{ type: "mane", scale: 0.8 }, { type: "tail", scale: 0.9 }]),
];

// ── Swimmer Profiles ───────────────────────────────────────────────

export const SWIMMER_PROFILES: readonly ModelProfile[] = [
  profile("CLOWNFISH", "Clownfish", "SWIMMER", 0xFF6622, 0xFFFFFF,
    { height: 0.4, width: 0.6, depth: 0.8 },
    { size: 0.9, shape: "sphere", yOffset: 0 },
    { thickness: 0.5, length: 0.5 },
    [{ type: "fin", scale: 0.6 }]),
  profile("GOLDFISH", "Goldfish", "SWIMMER", 0xFFAA22, 0xFF8800,
    { height: 0.4, width: 0.7, depth: 0.8 },
    { size: 0.9, shape: "sphere", yOffset: 0 },
    { thickness: 0.5, length: 0.5 },
    [{ type: "fin", scale: 0.8 }, { type: "tail", scale: 1.2 }]),
  profile("PUFFERFISH", "Pufferfish", "SWIMMER", 0xDDBB55, 0xAA8833,
    { height: 0.7, width: 1.3, depth: 1.3 },
    { size: 0.8, shape: "sphere", yOffset: 0 },
    { thickness: 0.4, length: 0.4 },
    [{ type: "fin", scale: 0.4 }]),
  profile("SHARK", "Shark", "SWIMMER", 0x667788, 0xAABBCC,
    { height: 0.7, width: 0.8, depth: 1.5 },
    { size: 0.8, shape: "pointed", yOffset: 0 },
    { thickness: 0.6, length: 0.7 },
    [{ type: "fin", scale: 1.5 }, { type: "tail", scale: 1.2 }]),
  profile("SWORDFISH", "Swordfish", "SWIMMER", 0x4466AA, 0x88AACC,
    { height: 0.5, width: 0.6, depth: 1.8 },
    { size: 0.7, shape: "pointed", yOffset: 0 },
    { thickness: 0.5, length: 0.5 },
    [{ type: "beak", scale: 2.0 }, { type: "fin", scale: 1.0 }]),
  profile("WHALE", "Whale", "SWIMMER", 0x445566, 0x556677,
    { height: 1.2, width: 1.4, depth: 2.0 },
    { size: 0.9, shape: "sphere", yOffset: 0 },
    { thickness: 0.8, length: 0.8 },
    [{ type: "fin", scale: 1.2 }, { type: "tail", scale: 1.5 }]),
];

// ── Fish Profiles ──────────────────────────────────────────────────

export const FISH_PROFILES: readonly ModelProfile[] = [
  profile("BASS", "Bass", "SWIMMER", 0x558844, 0x88AA66,
    { height: 0.5, width: 0.7, depth: 1.0 },
    { size: 0.8, shape: "sphere", yOffset: 0 },
    { thickness: 0.5, length: 0.5 },
    [{ type: "fin", scale: 0.8 }]),
  profile("BLUEGILL", "Bluegill", "SWIMMER", 0x3366AA, 0xFFCC44,
    { height: 0.5, width: 0.8, depth: 0.8 },
    { size: 0.8, shape: "sphere", yOffset: 0 },
    { thickness: 0.5, length: 0.5 },
    [{ type: "fin", scale: 0.7 }]),
  profile("CATFISH", "Catfish", "SWIMMER", 0x665544, 0x887766,
    { height: 0.5, width: 0.8, depth: 1.1 },
    { size: 0.9, shape: "flat", yOffset: 0 },
    { thickness: 0.6, length: 0.5 },
    [{ type: "fin", scale: 0.6 }]),
  profile("KOI", "Koi", "SWIMMER", 0xFF6633, 0xFFFFFF,
    { height: 0.5, width: 0.7, depth: 1.0 },
    { size: 0.8, shape: "sphere", yOffset: 0 },
    { thickness: 0.5, length: 0.5 },
    [{ type: "fin", scale: 0.9 }, { type: "tail", scale: 1.3 }]),
  profile("PIRANHA", "Piranha", "SWIMMER", 0x667766, 0xCC3322,
    { height: 0.5, width: 0.8, depth: 0.8 },
    { size: 0.9, shape: "sphere", yOffset: 0 },
    { thickness: 0.5, length: 0.5 },
    [{ type: "fin", scale: 0.6 }]),
  profile("SALMON", "Salmon", "SWIMMER", 0xCC7766, 0xDDAA99,
    { height: 0.5, width: 0.6, depth: 1.2 },
    { size: 0.8, shape: "sphere", yOffset: 0 },
    { thickness: 0.5, length: 0.5 },
    [{ type: "fin", scale: 0.7 }]),
  profile("TROUT", "Trout", "SWIMMER", 0x668855, 0xDDBB88,
    { height: 0.5, width: 0.6, depth: 1.1 },
    { size: 0.8, shape: "sphere", yOffset: 0 },
    { thickness: 0.5, length: 0.5 },
    [{ type: "fin", scale: 0.7 }]),
];

// ── Marine Mammal Profiles ─────────────────────────────────────────

export const MARINE_MAMMAL_PROFILES: readonly ModelProfile[] = [
  profile("DOLPHIN", "Dolphin", "SWIMMER", 0x6688AA, 0xAABBCC,
    { height: 0.6, width: 0.7, depth: 1.5 },
    { size: 0.8, shape: "pointed", yOffset: 0 },
    { thickness: 0.6, length: 0.6 },
    [{ type: "fin", scale: 1.0 }, { type: "tail", scale: 1.0 }]),
  profile("MANATEE", "Manatee", "SWIMMER", 0x778877, 0x667766,
    { height: 0.9, width: 1.3, depth: 1.5 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.8, length: 0.6 },
    [{ type: "tail", scale: 1.0 }]),
  profile("ORCA", "Orca", "SWIMMER", 0x222222, 0xEEEEEE,
    { height: 0.8, width: 0.9, depth: 1.6 },
    { size: 0.9, shape: "sphere", yOffset: 0 },
    { thickness: 0.7, length: 0.7 },
    [{ type: "fin", scale: 1.5 }, { type: "tail", scale: 1.2 }]),
  profile("SEALION", "Sea Lion", "SWIMMER", 0x886644, 0x775533,
    { height: 0.7, width: 1.0, depth: 1.2 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.8, length: 0.5 },
    [{ type: "tail", scale: 0.8 }]),
  profile("WALRUS", "Walrus", "SWIMMER", 0x886655, 0x997766,
    { height: 0.9, width: 1.3, depth: 1.3 },
    { size: 1.1, shape: "sphere", yOffset: 0 },
    { thickness: 0.9, length: 0.6 },
    [{ type: "tusks", scale: 1.0 }]),
];

// ── Slitherer Profiles ─────────────────────────────────────────────

export const SLITHERER_PROFILES: readonly ModelProfile[] = [
  profile("COBRA", "Cobra", "SLITHERER", 0x445533, 0xBBCC44,
    { height: 0.8, width: 1.3, depth: 1.0 },
    { size: 1.2, shape: "flat", yOffset: 0.15 },
    { thickness: 1.0, length: 1.0 },
    [{ type: "collar", scale: 1.8 }]),
  profile("GARDEN_SNAKE", "Garden Snake", "SLITHERER", 0x44AA44, 0xDDCC44,
    { height: 0.5, width: 0.7, depth: 0.8 },
    { size: 0.8, shape: "sphere", yOffset: 0 },
    { thickness: 0.7, length: 0.8 }, []),
  profile("PYTHON", "Python", "SLITHERER", 0x887744, 0x665533,
    { height: 0.7, width: 1.2, depth: 1.3 },
    { size: 1.0, shape: "sphere", yOffset: 0 },
    { thickness: 1.3, length: 1.2 }, []),
  profile("RATTLESNAKE", "Rattlesnake", "SLITHERER", 0xAA8855, 0x665533,
    { height: 0.6, width: 0.9, depth: 1.0 },
    { size: 0.9, shape: "pointed", yOffset: 0 },
    { thickness: 0.9, length: 1.0 },
    [{ type: "tail", scale: 0.5 }]),
  profile("WORM", "Worm", "SLITHERER", 0xCC7777, 0xAA5555,
    { height: 0.3, width: 0.5, depth: 0.6 },
    { size: 0.7, shape: "sphere", yOffset: 0 },
    { thickness: 0.8, length: 0.6 }, []),
];

// ── Prop Profiles ──────────────────────────────────────────────────

export const PROP_PROFILES: readonly ModelProfile[] = [
  profile("BOULDER", "Boulder", "PROP", 0x888888, 0x666666,
    { height: 0.7, width: 1.2, depth: 1.1 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 }, []),
  profile("BOOKCASE", "Bookcase", "PROP", 0x885533, 0xCC8844,
    { height: 1.5, width: 1.0, depth: 0.4 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 },
    [{ type: "shelf", scale: 3 }]),
  profile("CASTLE_TOWER", "Castle Tower", "PROP", 0x999999, 0x777777,
    { height: 2.5, width: 0.6, depth: 0.6 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 },
    [{ type: "flat_top", scale: 1.0 }]),
  profile("CHAIR", "Chair", "PROP", 0x885533, 0x774422,
    { height: 0.9, width: 0.5, depth: 0.5 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 }, []),
  profile("COUCH", "Couch", "PROP", 0x5555AA, 0x444488,
    { height: 0.7, width: 1.5, depth: 0.7 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 },
    [{ type: "cushion", scale: 1.0 }]),
  profile("DESK", "Desk", "PROP", 0x885533, 0x774422,
    { height: 0.75, width: 1.2, depth: 0.6 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 }, []),
  profile("FENCE", "Fence", "PROP", 0xAA8855, 0x997744,
    { height: 0.8, width: 2.0, depth: 0.1 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 }, []),
  profile("FIRE_HYDRANT", "Fire Hydrant", "PROP", 0xCC2222, 0xFFDD44,
    { height: 0.6, width: 0.3, depth: 0.3 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 },
    [{ type: "spout", scale: 1.0 }]),
  profile("LAMP", "Lamp", "PROP", 0xDDCC88, 0xFFEEAA,
    { height: 1.2, width: 0.4, depth: 0.4 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 },
    [{ type: "glow", scale: 1.0 }]),
  profile("LOVESEAT", "Loveseat", "PROP", 0xBB4444, 0x993333,
    { height: 0.7, width: 1.1, depth: 0.65 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 },
    [{ type: "cushion", scale: 0.8 }]),
  profile("MUSHROOM", "Mushroom", "PROP", 0xCC3322, 0xEEEECC,
    { height: 0.6, width: 0.5, depth: 0.5 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 },
    [{ type: "mushroom_cap", scale: 1.5 }]),
  profile("PIANO", "Piano", "PROP", 0x222222, 0xEEEEEE,
    { height: 1.0, width: 1.3, depth: 0.5 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 },
    [{ type: "piano_keys", scale: 1.0 }]),
  profile("SOFA", "Sofa", "PROP", 0x667744, 0x556633,
    { height: 0.7, width: 1.8, depth: 0.7 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 },
    [{ type: "cushion", scale: 1.2 }]),
  profile("TABLE", "Table", "PROP", 0x885533, 0x774422,
    { height: 0.75, width: 1.0, depth: 0.6 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 }, []),
  profile("TELEVISION", "Television", "PROP", 0x222222, 0x4488CC,
    { height: 0.6, width: 1.0, depth: 0.1 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 },
    [{ type: "screen", scale: 1.0 }]),
  profile("TREE", "Tree", "PROP", 0x885533, 0x338833,
    { height: 2.0, width: 0.3, depth: 0.3 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 },
    [{ type: "canopy", scale: 2.0 }]),
  profile("WELL", "Well", "PROP", 0x888888, 0x885533,
    { height: 0.8, width: 0.6, depth: 0.6 },
    { size: 0.0, shape: "sphere", yOffset: 0 },
    { thickness: 0.0, length: 0.0 }, []),
];

// ── Vehicle Profiles ───────────────────────────────────────────────

export const AUTOMOBILE_PROFILES: readonly ModelProfile[] = [
  profile("COMPACT_CAR", "Compact Car", "VEHICLE", 0x4488CC, 0x333333,
    { height: 0.8, width: 0.9, depth: 1.0 },
    STD_HEAD, STD_LIMBS, []),
  profile("CONVERTIBLE", "Convertible", "VEHICLE", 0xCC2222, 0x333333,
    { height: 0.7, width: 1.0, depth: 1.1 },
    STD_HEAD, STD_LIMBS, []),
  profile("PICKUP_TRUCK", "Pickup Truck", "VEHICLE", 0x445566, 0x333333,
    { height: 1.1, width: 1.1, depth: 1.3 },
    STD_HEAD, STD_LIMBS,
    [{ type: "flatbed", scale: 1.0 }]),
  profile("POLICE_CAR", "Police Car", "VEHICLE", 0x222222, 0xEEEEEE,
    { height: 0.85, width: 1.0, depth: 1.1 },
    STD_HEAD, STD_LIMBS,
    [{ type: "light_bar", scale: 1.0 }]),
  profile("SEDAN", "Sedan", "VEHICLE", 0x666666, 0x333333,
    { height: 0.85, width: 1.0, depth: 1.15 },
    STD_HEAD, STD_LIMBS, []),
  profile("SUV", "SUV", "VEHICLE", 0x224422, 0x333333,
    { height: 1.15, width: 1.1, depth: 1.2 },
    STD_HEAD, STD_LIMBS,
    [{ type: "bumper", scale: 1.0 }]),
  profile("TAXI", "Taxi", "VEHICLE", 0xFFCC00, 0x222222,
    { height: 0.85, width: 1.0, depth: 1.1 },
    STD_HEAD, STD_LIMBS, []),
  profile("VAN", "Van", "VEHICLE", 0xEEEEEE, 0x555555,
    { height: 1.2, width: 1.1, depth: 1.3 },
    STD_HEAD, STD_LIMBS,
    [{ type: "box_car", scale: 1.0 }]),
];

export const AIRCRAFT_PROFILES: readonly ModelProfile[] = [
  profile("BIPLANE", "Biplane", "VEHICLE", 0xCC8822, 0x885511,
    { height: 0.8, width: 1.5, depth: 1.0 },
    STD_HEAD, STD_LIMBS,
    [{ type: "wings", scale: 1.5 }, { type: "propeller", scale: 0.8 }]),
  profile("HELICOPTER", "Helicopter", "VEHICLE", 0x446644, 0x333333,
    { height: 1.0, width: 0.8, depth: 1.2 },
    STD_HEAD, STD_LIMBS,
    [{ type: "rotor", scale: 2.0 }]),
  profile("HOT_AIR_BALLOON", "Hot Air Balloon", "VEHICLE", 0xFF4444, 0xFFCC00,
    { height: 2.0, width: 1.5, depth: 1.5 },
    STD_HEAD, STD_LIMBS,
    [{ type: "balloon", scale: 2.5 }]),
  profile("JET", "Jet", "VEHICLE", 0xCCCCCC, 0x4466AA,
    { height: 0.7, width: 1.2, depth: 1.5 },
    STD_HEAD, STD_LIMBS,
    [{ type: "wings", scale: 1.3 }]),
  profile("PROPELLER_PLANE", "Propeller Plane", "VEHICLE", 0xEEEEEE, 0xCC2222,
    { height: 0.7, width: 1.4, depth: 1.2 },
    STD_HEAD, STD_LIMBS,
    [{ type: "wings", scale: 1.4 }, { type: "propeller", scale: 1.0 }]),
  profile("UFO", "UFO", "VEHICLE", 0x99AACC, 0x44FFAA,
    { height: 0.4, width: 2.0, depth: 2.0 },
    STD_HEAD, STD_LIMBS,
    [{ type: "glow", scale: 1.5 }]),
];

export const WATERCRAFT_PROFILES: readonly ModelProfile[] = [
  profile("CANOE", "Canoe", "VEHICLE", 0x885522, 0x774411,
    { height: 0.4, width: 0.5, depth: 1.5 },
    STD_HEAD, STD_LIMBS, []),
  profile("PIRATE_SHIP", "Pirate Ship", "VEHICLE", 0x664422, 0xEEEECC,
    { height: 1.5, width: 1.0, depth: 2.0 },
    STD_HEAD, STD_LIMBS,
    [{ type: "mast", scale: 2.0 }, { type: "sail", scale: 1.5 }]),
  profile("ROWBOAT", "Rowboat", "VEHICLE", 0x997744, 0x886633,
    { height: 0.4, width: 0.6, depth: 1.2 },
    STD_HEAD, STD_LIMBS, []),
  profile("SAILBOAT", "Sailboat", "VEHICLE", 0xEEEEEE, 0x3366CC,
    { height: 1.2, width: 0.6, depth: 1.3 },
    STD_HEAD, STD_LIMBS,
    [{ type: "mast", scale: 1.5 }, { type: "sail", scale: 1.2 }]),
  profile("SPEEDBOAT", "Speedboat", "VEHICLE", 0xCC2222, 0xEEEEEE,
    { height: 0.5, width: 0.7, depth: 1.4 },
    STD_HEAD, STD_LIMBS, []),
  profile("SUBMARINE", "Submarine", "VEHICLE", 0x445566, 0x333344,
    { height: 0.6, width: 0.7, depth: 1.8 },
    STD_HEAD, STD_LIMBS,
    [{ type: "periscope", scale: 1.0 }, { type: "fin", scale: 0.8 }]),
  profile("YACHT", "Yacht", "VEHICLE", 0xEEEEEE, 0x2244AA,
    { height: 0.8, width: 0.8, depth: 1.6 },
    STD_HEAD, STD_LIMBS,
    [{ type: "cabin_tall", scale: 1.0 }]),
];

export const TRAIN_PROFILES: readonly ModelProfile[] = [
  profile("CABOOSE", "Caboose", "VEHICLE", 0xCC2222, 0x882222,
    { height: 1.0, width: 0.8, depth: 1.0 },
    STD_HEAD, STD_LIMBS,
    [{ type: "cabin_tall", scale: 0.8 }]),
  profile("COAL_CAR", "Coal Car", "VEHICLE", 0x444444, 0x333333,
    { height: 0.7, width: 0.8, depth: 1.0 },
    STD_HEAD, STD_LIMBS,
    [{ type: "tank", scale: 1.0 }]),
  profile("FREIGHT_CAR", "Freight Car", "VEHICLE", 0x886633, 0x664422,
    { height: 0.9, width: 0.8, depth: 1.2 },
    STD_HEAD, STD_LIMBS,
    [{ type: "box_car", scale: 1.0 }]),
  profile("LOCOMOTIVE", "Locomotive", "VEHICLE", 0x333333, 0xCC2222,
    { height: 1.1, width: 0.9, depth: 1.5 },
    STD_HEAD, STD_LIMBS,
    [{ type: "smokestack", scale: 1.0 }, { type: "wheels_large", scale: 1.0 }]),
  profile("PASSENGER_CAR", "Passenger Car", "VEHICLE", 0x4466AA, 0xCCCCCC,
    { height: 0.9, width: 0.8, depth: 1.5 },
    STD_HEAD, STD_LIMBS,
    [{ type: "box_car", scale: 1.0 }]),
  profile("TANK_CAR", "Tank Car", "VEHICLE", 0xCCCCCC, 0x888888,
    { height: 0.8, width: 0.8, depth: 1.2 },
    STD_HEAD, STD_LIMBS,
    [{ type: "tank", scale: 1.2 }]),
];

// ── Lookup ─────────────────────────────────────────────────────────

const ALL_PROFILES: readonly ModelProfile[] = [
  ...BIPED_PROFILES,
  ...FLYER_PROFILES,
  ...QUADRUPED_PROFILES,
  ...SWIMMER_PROFILES,
  ...FISH_PROFILES,
  ...MARINE_MAMMAL_PROFILES,
  ...SLITHERER_PROFILES,
  ...PROP_PROFILES,
  ...AUTOMOBILE_PROFILES,
  ...AIRCRAFT_PROFILES,
  ...WATERCRAFT_PROFILES,
  ...TRAIN_PROFILES,
];

const PROFILE_BY_ID = new Map<string, ModelProfile>(
  ALL_PROFILES.map(p => [p.id, p]),
);

/** Looks up a model profile by ID. Returns undefined if not found. */
export function getModelProfile(id: string): ModelProfile | undefined {
  return PROFILE_BY_ID.get(id);
}

/** Returns all model profiles. */
export function getAllModelProfiles(): readonly ModelProfile[] {
  return ALL_PROFILES;
}

/** Returns profiles for a given category (includes sub-categories). */
export function getProfilesByCategory(category: EntityCategory): readonly ModelProfile[] {
  return ALL_PROFILES.filter(p => p.category === category);
}
