export {
  BASE_MODEL_CLASS_DATA,
  MODEL_CLASS_DATA,
  type BaseModelClassData,
  type KnownModelClassKey,
  type LoadedModelResource,
  type ModelBrowserNode,
  type ModelClassData,
  type ModelClassInfo,
  type ModelClassInfoSource,
  type ModelDiscoveryOptions,
  type ModelGeometryData,
  type ModelJointDefinition,
  type ModelResourceDefinition,
  type ModelResourceLoadResult,
  type ModelResourceSummary,
} from "./model-resources/definitions.js";
export {
  buildJointHierarchy,
  camelCaseToEnum,
  enumToCamelCase,
  getArrayEntries,
  getArrayIndexForJoint,
  getArrayNameForJoint,
  getDefaultTextureEnumName,
  getTextureResourceFileName,
  getThumbnailResourceFileName,
  getVisualResourceFileNameFromModelName,
  hasArray,
  isEnumName,
  isRootJoint,
  makeCodeReadyJointDefinitions,
  makeEnumName,
} from "./model-resources/helpers.js";
export { ModelResourceCatalog } from "./model-resources/catalog.js";
export {
  AircraftResource,
  AutomobileResource,
  BipedResource,
  FishResource,
  FlyerResource,
  MarineMammalResource,
  PropResource,
  QuadrupedResource,
  SlithererResource,
  SwimmerResource,
  TrainResource,
  VehicleResource,
  WatercraftResource,
  type IndividualModelResource,
} from "./model-resources/individual-resources.js";
